### ISSUE TITLE
Use babel-preset-env instead of babel presets

### ISSUE THREAD

**Issue by floo51** [marmelab/comfygure#4]

**Comment by arturparkhisenko** [comment]
@floo51 @Kmaschta can I take it? Already started :)

**Comment by arturparkhisenko** [comment]
Saw Travis build errors, fixing it :)

**Comment by Kmaschta** [comment]
Hi ! Sure you can take it.
I'll take a look at your PR later this day.

**Comment by arturparkhisenko** [comment]
@Kmaschta can you check my pull request? and I'll continue working with API part ;)

**Comment by Kmaschta** [comment]
Sorry for the delay, it is good for the admin!

**Comment by arturparkhisenko** [comment]
@Kmaschta for the API part https://github.com/marmelab/comfygure/pull/114
