### ISSUE TITLE
What about the storage of booleans?

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/comfygure#94]
Let's have the following example:

```bash
> cat '{ "myvar": false }' > test.json
> comfy add production -f test.json
```

What is retrieved will depends on the format:

```bash
> comfy get production --envars
MYVAR='false'

```

```bash
> comfy get production --yml
myvar: false

```

```bash
> comfy get production --json
{
    "myvar": "false"
}
```

As you can see in JSON and environment variables, the boolean `false` is transformed in string.
This is a problem, especially in JSON, because:

```js
Boolean('false') === true
```

And I'm not sure how to handle this case.

**Comment by fzaninotto** [comment]
JSON deals with booleans properly. `{ foo: true } != { foo: 'true' }`. The problem lies somewhere in the comfygure code, which does a conversion it should not do.

**Comment by Kmaschta** [comment]
I introduced a way to serialize the configuration values.
For now, it's as simple as a `JSON.stringify` but it'll can be improved later if needed.
