### ISSUE TITLE
Delete old entry configuration

### ISSUE THREAD

**Issue by zyhou** [marmelab/comfygure#95]
Let's have the following example:
```
"parent": {
 "entry": "value"
}
```

I update my configuration like this:
```
"parent": {
 "child1": {
  "entry": "value"
 },
"child2": {
  "entry": "value"
 }
}
```

In database, `parent.entry.value` is not deleted, but the link with my configuration is removed.
The problem comes from `get`.

**Comment by Kmaschta** [comment]
I think it's fixed with this commit https://github.com/marmelab/comfygure/commit/59519244bc634a4b4aad39df069418e4994c71f3#diff-ab30177faeaba560501f19808d168b16 but not deployed yet.

To be sure, we can add a test.

**Comment by zyhou** [comment]
Ah, I'm not sure we use the last version on the project. Ok I check test

**Comment by zyhou** [comment]
Thanks, we just need to update comfy version on my project
